// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-g2Pkd_gFN8kSXHEqRDfsoSin1ZIrqrY',
    appId: '1:745286878699:web:2453e74d009421005005ae',
    messagingSenderId: '745286878699',
    projectId: 'chatter-flutter-chat-app',
    authDomain: 'chatter-flutter-chat-app.firebaseapp.com',
    storageBucket: 'chatter-flutter-chat-app.appspot.com',
    measurementId: 'G-6QFQ634RMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr9dmyKrsrfEISUV8v5qWD0gGf9pJjPzI',
    appId: '1:745286878699:android:7493d204213659c85005ae',
    messagingSenderId: '745286878699',
    projectId: 'chatter-flutter-chat-app',
    storageBucket: 'chatter-flutter-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDynNEtslqem4pOhb_gSKHXWaWGAgQ9gyI',
    appId: '1:745286878699:ios:041c05b0f91f4b565005ae',
    messagingSenderId: '745286878699',
    projectId: 'chatter-flutter-chat-app',
    storageBucket: 'chatter-flutter-chat-app.appspot.com',
    androidClientId: '745286878699-r2gg5k2u6an685orov17u4cdq0avkkhr.apps.googleusercontent.com',
    iosClientId: '745286878699-2i72b84h2jjpvbk5d5f31hniau0rll0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatterFlutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDynNEtslqem4pOhb_gSKHXWaWGAgQ9gyI',
    appId: '1:745286878699:ios:041c05b0f91f4b565005ae',
    messagingSenderId: '745286878699',
    projectId: 'chatter-flutter-chat-app',
    storageBucket: 'chatter-flutter-chat-app.appspot.com',
    androidClientId: '745286878699-r2gg5k2u6an685orov17u4cdq0avkkhr.apps.googleusercontent.com',
    iosClientId: '745286878699-2i72b84h2jjpvbk5d5f31hniau0rll0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatterFlutterChatApp',
  );
}
